# Step 1: Build Astro app
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Serve the built static files
FROM node:20-alpine

RUN npm install -g serve

WORKDIR /app

COPY --from=build /app/dist /app

EXPOSE 5001

CMD ["serve", "-s", ".", "-l", "5001"]