# Step 1: Build Astro app
FROM node:20 AS build

ARG PUBLIC_ENVIRONMENT
ARG PUBLIC_BACKEND_URL
ARG PUBLIC_FIREBASE_API_KEY
ARG PUBLIC_FIREBASE_AUTH_DOMAIN
ARG PUBLIC_FIREBASE_PROJECT_ID
ARG PUBLIC_FIREBASE_APP_ID

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Serve the built static files
FROM node:20-alpine

RUN npm install -g serve

WORKDIR /app

COPY --from=build /app/dist /app

EXPOSE 5001

CMD ["serve", ".", "-l", "5001"]